name: Build Tailscale HND

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x tailscale/build_hnd.sh
          ./tailscale/build_hnd.sh
